POST http://localhost:9000/products HTTP/1.1
content-type: application/json

{
   "name": "Điện thoại Iphone 15",
   "price": 15600000,
   "discount": 15,
   "stock": 15,
   "categoryId": "643e049e37b0db7eb875b0dc",
   "supplierId": "643e051b37b0db7eb875b0ed"
}