POST http://localhost:9000/customers HTTP/1.1
content-type: application/json

{ 
   "firstName": "Customer", 
   "lastName": "D",
   "email": "customer_d@gmail.com",
   "phoneNumber": "0386592444",
   "address": "340 dien bien phu",
   "birthday": "1990-2-2"
}