POST http://localhost:9000/employees HTTP/1.1
content-type: application/json

{ 
   "firstName": "Employee", 
   "lastName": "a",
   "email": "employee_a@gmail.com",
   "password": "123456",
   "phoneNumber": "0386592521",
   "address": "455 ha huy tap"
}